USE DATABASE user;

DROP TABLE IF EXISTS User;
 
CREATE TABLE UserInfo (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  emailid VARCHAR(250) NOT NULL,
  role VARCHAR(250) DEFAULT NULL
);